//-------------------------------------------------------------------------------------------------
// <copyright file="DQService.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//
// <summary>
//     Delta Query sample Windows service.
// 
//     This source is subject to the Sample Client End User License Agreement
//     included in this project.
// </summary>
//
// <remarks />
//
// <disclaimer>
//     THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
//     EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED 
//     WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
// </disclaimer>
//
// <auto-generated />
//-------------------------------------------------------------------------------------------------

namespace DeltaQueryWindowsService
{
    partial class ProjectInstaller
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.DQServiceProcessInstaller = new System.ServiceProcess.ServiceProcessInstaller();
            this.DQServiceInstaller = new System.ServiceProcess.ServiceInstaller();
            // 
            // DQServiceProcessInstaller
            // 
            this.DQServiceProcessInstaller.Account = System.ServiceProcess.ServiceAccount.LocalService;
            this.DQServiceProcessInstaller.Password = null;
            this.DQServiceProcessInstaller.Username = null;
            // 
            // DQServiceInstaller
            // 
            this.DQServiceInstaller.Description = "Delta Query Service";
            this.DQServiceInstaller.DisplayName = "Delta Query Service";
            this.DQServiceInstaller.ServiceName = "DeltaQueryService";
            this.DQServiceInstaller.StartType = System.ServiceProcess.ServiceStartMode.Automatic;
            // 
            // ProjectInstaller
            // 
            this.Installers.AddRange(new System.Configuration.Install.Installer[] {
            this.DQServiceProcessInstaller,
            this.DQServiceInstaller});

        }

        #endregion

        private System.ServiceProcess.ServiceProcessInstaller DQServiceProcessInstaller;
        public System.ServiceProcess.ServiceInstaller DQServiceInstaller;
    }
}